# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-29 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('match_status', models.CharField(choices=[('1', 'Win'), ('2', 'Draw')], default='2', max_length=2)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_point', to='cricket.Match')),
            ],
            options={
                'verbose_name': 'MatchPoint',
                'verbose_name_plural': 'MatchPoints',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('firstname', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Name')),
                ('lastname', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Name')),
                ('image_uri', models.CharField(blank=True, max_length=1000, verbose_name='Player Image')),
                ('jersy_number', models.PositiveIntegerField(default=0, verbose_name='jersy_number')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='Matches Played')),
                ('total_run', models.PositiveIntegerField(default=0, verbose_name='Matches Played')),
                ('highest_score', models.PositiveIntegerField(default=0, verbose_name='Highest Score')),
                ('fifties', models.PositiveIntegerField(default=0, verbose_name='Fifties')),
                ('hundreds', models.PositiveIntegerField(default=0, verbose_name='hundreds')),
                ('wickets', models.PositiveIntegerField(default=0, verbose_name='Wickets')),
                ('run_rate', models.FloatField(default=0, verbose_name='Run Rate')),
                ('strike_rate', models.FloatField(default=0, verbose_name='Strike Rate')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_history', to='cricket.Player')),
            ],
            options={
                'verbose_name': 'PlayerHistory',
                'verbose_name_plural': 'PlayerHistory',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Name')),
                ('logo_uri', models.CharField(blank=True, max_length=1000, verbose_name='Logo')),
                ('club_state', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='matchpoint',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_point', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_team', to='cricket.Team'),
        ),
    ]
